#+TITLE: Anthropology of Energy: Literatures 
#+AUTHOR: by C.H.
#+DATE: 2019-02-08

#+TOC: headlines 2

* Beginnings
** /Theory/: The Evolution of Culture 
*** Leslie White (1900--1975)
 - Energy anthropology, or the anthropology of energy, is usually said to have originated with Leslie @white:1943aa.
   - White was a forceful proponent of the centrality of energy in human affairs. He saw energy as a prime mover and way of explaining what happens in human life, and especially in the evolution of human societies and culture.  
   - In /[[https://drive.google.com/a/yale.edu/file/d/1IBbgdYjSuw2rpzJN77Fvstf2pNoCJnI0/view?usp=drivesd][Energy and the Evolution of Culture]]/ he modeled an mode of anthropological theorizing that he hoped would show cultural anthropology to be, at base, a natural science. 
     - "The purpose of culture is to serve the needs of man... by drawing upon resources within the human organism alone..... [and] by drawing upon the resources of the external world" \cite*[335]{white:1943aa}.
     - His argumentation was mathematical in its rhetoric.
       - White isolated constants and variables, arguing that it was with the variables we should be concerned should we want to understand the "material, mechanical means with which man exploits the resources of nature" @white:1943aa.
         - "...the satisfaction of human needs from the 'inner resources' may be regarded as a constant, the satisfaction of needs from the outer resources a variable" [@white:1943aa p. 336].
         - "...we may regard the human race... as a constant..."
         - "...we may regard habitat as a constant..."
   - Of the /variables/ ---- that is, those aspects of human existence which change, as opposed to those that don't ---- White listed three, each turning on energy:
     1. The /amount of energy per capita per unit/ of time harnessed and put to work within the culture,
     2. The technological /means/ with which this energy is expended
     3. The human need-serving /product that accrues/ from the expenditure of energy.

*** Julian Steward
* References
 - All referenced documents can be found in [[https://drive.google.com/drive/folders/11VAyGIgfx7l57NQRRElpLsyMr8lY4bqq?usp=sharing][this archive]].
