#+TITLE: Funding

* Finding Aids
--- Am Anth. Assoc.: http://careercenter.aaanet.org/jobs
--- GrantFoward: https://www.grantforward.com
--- Jobs UK: https://jobs.ac.uk
--- Academic Positions EU: https://academicpositions.com 
* Professorships
* Post-Doctoral Positions
*** American Academy of Arts and Sciences
**** Visiting Scholars Program
     DEADLINE: <2019-10-01 Tue>
The Academy’s Visiting Scholars Program provides residential fellowships to postdoctoral scholars in the humanities and social sciences. The fellowship program offers a collaborative work environment and the opportunity to interact with Academy members. It also creates a national network for these scholars, assisting them in their research and professional development.

Applications for the cycle of fellowships to begin in Fall 2020 will be accepted in October 2019.

Housed at the headquarters of the Academy in Cambridge, Massachusetts, Visiting Scholars participate in Academy-sponsored conferences, seminars, and informal gatherings while advancing their scholarly research. The program also provides Visiting Scholars with the opportunity to develop their professional skills through involvement in the programmatic work of the Academy. This could include pursuing research for a project committee, assisting in the preparation of an issue of Dædalus, helping to organize a conference or a symposium, or other comparable activities. The Academy provides office space and computer services as well as library privileges in cooperation with the Mahindra Humanities Center at Harvard University. The program also features a mentorship program that will pair each Visiting Scholar with an Academy Fellow who is an expert in a similar field of study.

The fellowship is a one-year post-doctoral fellowship with a mutual option to renew for a second year. To be eligible, candidates must have received the Ph.D. degree no more than four (4) years before the application deadline date, must have the degree in hand no later than August 1, 2020. Applicants may not hold a tenure-track teaching appointment nor have previously published a scholarly monograph. The annual stipend is $60,000, plus health insurance.
**** Mandel Presidential Fellows
**** Hellman Science and Technology Fellows
     https://www.amacad.org/about/fellowships
*** Berkeley
**** President's Postdoctoral Fellows 
     DEADLINE: <2019-11-11 Mon>
 https://ppfp.ucop.edu/info/how-to-apply/index.html
**** Chancellor's Postdoctoral Fellows
**** Ciriacy-Wantrup Postdoctoral Fellows
     DEADLINE: <2019-12-01 Sun>
 https://nature.berkeley.edu/academics/ciriacy-wantrup

 The S.V. Ciriacy-Wantrup Postdoctoral Fellowships in Natural Resource Economics and Political Economy will be awarded for the 2019-2020 academic year to support advanced research at the University of California, Berkeley.

 For the purposes of this fellowship, natural resources are defined broadly to include environmental resources. The fellowship encourages, but is not limited to, policy-oriented research. Applications are open to scholars from any social science discipline, and related professional fields such as law and planning, who will make significant contributions to research on natural resource economics broadly defined. Preference will be given to proposals whose orientation is broadly institutional and/or historical, and which are conceptually and theoretically innovative. Proposals whose primary emphasis is on advancing statistical or econometric theory are not eligible for consideration.

 The purpose of the fellowship is to develop new and innovative intellectual connections and ideas in natural resources economics and political economy at UC Berkeley. Accordingly, Applicants should provide specific information about the project proposed for the fellowship period, and explain why support from the fellowship and the opportunity to work at Berkeley are important for the success of that project. We welcome proposals from applicants who have not received their PhD at UC Berkeley. Proposals from UC Berkeley doctoral graduates that outline a significant change in research direction and that indicate engagement with different disciplines and faculty from those pursued during the doctoral program will be considered.

 Two types of awards are available:

 1. A one-year postdoctoral award with a salary of $58,040, renewable for a second year based on performance and funding availability. It is expected that the applicant will possess a recent doctorate or equivalent international degree by the appointment start date. Postdoctoral Fellows are appointed as UC employees and are governed by the UC Policy on Postdoctoral Scholars located here.

 2. A one-year award with a salary of $58,040 to support a professional leave from an academic or professional position, without option to renew. Applicatns for visiting research fellowships must have received their doctorate or equivalent international degree within the last ten years (not including any temporary leave time due to personal or family circumstances). Applicants must provide documentation of the home institution's or agency's concurrence of their leave. Visiting Research Fellows are appointed as UC employees and are governed by the UC Policy on Visiting Appointments located here.

 Both types of fellowships include $2,000 toward research-related expenses and one-way economy airfare to Berkeley for each fellow and his/her immediate family.

 Application Procedure
 Applications must be received by December 3, 2018.

 A complete application consists of the following:

 Cover Letter (Required): 1-2 page cover letter indicating your preferred Departmental affiliation and/or faculty mentor
 Curriculum Vitae (Required): Your current C.V.
 Abstract (Required): 1 paragraph abstract
 Research proposal (Required): Not to exceed 10 pages
 Publications (Required): 1 or more recent publications
 Three letters of recommendation (visible to all reviewers) from faculty members familiar with the candidate's research. Applicants should ask referees to review the UC Berkeley Statement of Confidentiality
 Applicants for the Visiting Research Fellowship must include a statement from their home institution concurring with the leave of absence for the duration of the fellowship term.
 To Apply: 

 https://aprecruit.berkeley.edu/apply/JPF01890

 Questions may be directed to Ruxin Liu by e-mail at ruxinl@berkeley.eduor by phone at (510) 643-9579.

 We would greatly appreciate your letting us know how you found out about this award. Send a brief note to ruxinl@berkeley.edu.

 Fellowship Policies
 Conditions of the Fellowship
 Appointments are expected to begin one week before the academic semester begins, for one year. Adjustments for those Fellows from institutions on a different calendar will be made. The Fellow must maintain residency at the University of California, Berkeley, during the appointment period. Postdoctoral and Visiting Research Fellows are prohibited from accepting employment and augmentation of salary during this fellowship period. Violation of this condition will result in the award being revoked and reimbursement of the full award amount. However, an appointee may, without paying tuition and fees, audit classes and participate with the consent of the instructor.

 Proof of Degree
 Thirty days before an appointment may be confirmed, the applicant must submit a copy of an official certification showing completion of the doctoral degree or equivalent international degree, or evidence that this degree has been conferred.

 Reimbursement for Travel to Berkeley
 The Fellowship will pay for one-way economy airfare to Berkeley for the Fellow and his/her immediate family.

 Research Allowance
 The amount of $2,000 will be available to the Fellow through the host department for field research, conference travel, or related expenses such as miscellaneous office expenses, photocopying, telephone, supplies, and mailing costs. The Fellow may use the research allowance at his/her discretion within University policy.

 Equipment Purchases
 Fellows may choose to use their research funds to purchase equipment such as a computer and related supplies. Fellows should be aware that the University requires that all equipment purchased with University funds remain the property of the University. The Fellow may submit a request in writing to their administrating department requesting to keep the equipment.

 Vacation and Academic Travel
 Only one trip of more than a week’s duration may be taken during the Fall and Spring semesters for research purposes. Should a Fellow request a longer research trip that cannot be accommodated during the recess periods, a formal request should be submitted to the Chair. Subsequent travel (funds permitting) may be undertaken only if an academic paper will be delivered. The Fellow is responsible for informing their sponsoring department of their whereabouts when traveling.

 Postdoctoral Research Fellows do not accrue vacation, however fellows are allowed time off each academic year in the intersession and recess periods (which constitutes about four weeks, excluding University holidays) between the beginning of Fall Term and the end of Spring Term. More information regarding leave for Potdoctoral Fellows can be located here.

 Visiting Research Fellows appointed on a fiscal year basis accrue vacation at the rate of two working days per month for full-time service. Appointees at 50 percent or more time accrue vacation at a proportionate rate; appointees at less than 50 percent time do not accrue vacation. Fellows must obtain approval from their faculty mentor prior to the use of vacation leave. More information regarding vacation leave can be located here.

 Health Insurance
 It is expected that all fellowship recipients maintain health coverage during the entire term of the Fellowship. Eligibility for health coverage through the University is dependant on the Fellowship type.

 Postdoctoral Research Fellows are covered by the UC Postdoc Scholar Benefits Plan (PSBP) and are entitled to health insurance, including dental, vision, short-term disability, life, and AD&D, through the University.

 Visiting Research Fellows are covered by the UC sponsored benefits plan (Mid-level coverage) and are entitled to health insurance, including medical, life, and AD&D, through the University (AD&D plan requires an employee paid premium). Visiting Research Fellows are not entitled to dental, vision or short-term disability.

 Performance Requirements
 While in residence, Fellows are expected to be active participants in the academic life of their host units, through attendance at seminars relevant to their area of study and interaction with other Fellows and designated faculty mentors. Fellows are expected to give at least one seminar a year on their research in a forum to be determined in consultation with their mentor. The time and place for this seminar must be communicated to the Ciriacy-Wantrup Fellowship coordinator, Ruxin Liu, in advance with a sufficient amount of time to notify other Fellows in residence and the members of the review committee. Fellows will be expected to attend seminars given by all other Fellows. All publications written or substantially developed during the term of the fellowship must formally acknowledge the support of the Ciriacy-Wantrup Fellowship in the publication(s). A final copy of all material developed as a result of Ciriacy-Wantrup Fellowship must be submitted to the Ciriacy-Wantrup Fellowship coordinator, Ruxin Liu, for inclusion in the Ciriacy-Wantrup Fellowship library.

 Renewing the Postdoctoral Wantrup Fellowship
 The selection committee bases renewal decisions on evidence of progress toward the Fellow's research goals. Applications for renewal must include 1) a cover letter from the Fellow summarizing his/her progress toward the original proposal and research goals; 2) a letter of support from the Fellow's Mentor; 3) confirmation from the sponsoring Department Chair that space will continue to be available for the Fellow in the second year; and 4) copies of any papers or articles completed and/or published during the first year of the Fellowship. Supplementary items such as letters of recommendation, reports of papers delivered, or non-project-related research are all welcome if they serve to strengthen the case for renewal. Continued affiliation with the host department is at the discretion of the host department.

 Administration
 An additional $1,500 will be transferred to the sponsoring department to compensate their administrative efforts required for hiring, obtaining visas (when necessary), and other administrative support.

 Postdoctoral appointments are governed by U.C. Policy for postdoctoral scholars (APM 390).

*** Brown
**** Watson Institute Fellows
**** Presidential Diversity Fellows
**** Critical Cultural Heritage Fellows
*** Cal East Bay
**** Assistant Professor of Environmental Anthropology
http://www.csueastbay.edu/oaa/jobs/csueb.html
https://apply.interfolio.com/61640
*** Cambridge
**** Career Development Fellows
**** Post-doctoral fellowships
     https://www.socanth.cam.ac.uk/socanth-research/post-doc-funding
*** Chicago
**** Chicago Society of Fellows
***** (x Sept. 2019)
  https://societyoffellows.uchicago.edu/https%3A//fellows.uchicago.edu

**** Chicago Provost's Fellows
 https://provostpostdoc.uchicago.edu/
*** Columbia
**** Earth Institute Fellows
**** Faculty
***** Ben Orlove
***** Bryan Boyd
*** Cornell
**** Cornell Mellon Fellows
     DEADLINE: <2019-10-01 Tue>
  https://societyhumanities.as.cornell.edu/mellon-postdoctoral-fellowships
  The Society for the Humanities will sponsor two postdoctoral teaching-research fellowships in the humanities, each awarded for the two-year period beginning August 2019. Each fellowship offers a stipend of $53,000/year. While in residence at Cornell, Mellon Fellows hold department affiliations and joint appointments with the Society for the Humanities, have limited teaching duties, and the opportunity for scholarly work. Mellon Postdoctoral Fellowships are available in two areas of specialization: Linguistics and Science & Technology Studies.
*** Dartmouth
**** Dartmouth Humanities Fellows
     SCHEDULED:   
   SCHEDULED: <2019-10-01 Tue> DEADLINE: <2019-10-01 Tue>
  PROGRAM DETAILS
  With the generous support of the Andrew W. Mellon Foundation, Dartmouth is pleased to accept applications for two postdoctoral fellowships in the humanities and humanistic social sciences from Fall 2019 to the end of Spring 2021. These fellowships foster the academic careers of scholars who have recently received their Ph.D. degrees by permitting them to pursue their research while gaining mentored experience as teachers and members of the departments and/or programs in which they are housed. The program also benefits Dartmouth by complementing existing curricula with underrepresented fields.

  We are currently not accepting applications for Anthropology; Asian and Middle Eastern Studies; Theater; Asian Societies, Cultures, and Languages; History; and Russian. Applicants must focus on materials customarily associated with research in the humanities or employ methods common in humanistic research.

  TERMS OF APPOINTMENT
  Fellows are expected to teach two courses in their home department(s) or program(s) in each year of their residency. At least one of the four courses should contribute something new to the Dartmouth curriculum, and at least one should be an introductory lecture course. Fellows will not, however, be asked to teach basic language courses.

  The appointed fellows will enjoy full use of such college resources as the library, computing center, the Leslie Center for the Humanities, Rockefeller Center for Public Policy and the Social Sciences, the Dickey Center for International Understanding, the Hood Museum of Art, and the Hopkins Center.

  The 2018-2020 fellows received an annual stipend of $57,528 plus benefits, an annual research allowance of $2,000, and a first-year-only computer allowance of $2,500. The terms for the 2019-2021 fellows will be similar.

  Applicants for the 2019-2021 fellowships must have completed a Ph.D. no earlier than January 1, 2017. Candidates who do not yet hold a Ph.D. but expect to by June 30, 2019 should supply a letter from their home institution corroborating such a schedule.
**** McKennen Anthropology Postdoctoral Fellows
     [] https://anthropology.dartmouth.edu/research/mckennan-postdoc-fellowship
*** Harvard
**** Harvard Society of Fellows
***** (11 August 2019, by nomination only)
  https://sites.fas.harvard.edu/~socfell/nominations.html

  HARVARD UNIVERSITY
  About the Society	
 	 	 	
  NOMINATION PROCEDURE
      Candidates are nominated for Junior Fellowships, generally by those under whom they have studied. Applications are not accepted from the candidates themselves. A letter of nomination should include an assessment of the candidate's work and promise, i.e. a full letter of recommendation, and also provide complete contact information for the candidate, including current residential address and email address, and the names, mailing addresses, and email addresses of three additional people who agree to write letters of recommendation by the date requested when they are contacted by the Society. Men and women interested in any field of study are eligible for these fellowships. Nominees should be of the highest calibre of intellectual achievement, i.e. comparable to the most successful candidates for junior faculty positions at leading universities.

      Upon receipt of the mailed nomination, the Society will request letters of recommendation from the referees listed, and ask the candidate to submit samples of written work (dissertation chapters, articles, papers) along with a one or two-page proposal describing the studies he or she would like to pursue while a Junior Fellow: 

   • The Society will request that the three additional letters of recommendation be submitted
      electronically - not by email, but through a link which we will provide in our correspondence with 
      the referees. After receipt of the nomination, the referees will be contacted by our office both by regular 
      mail and email and asked to submit their letters within three weeks of the date of our email. 
      (This is why full and accurate email addresses are necessary to process the nomination.) Instructions 
      for uploading letters will be provided to each referee, along with a password to enter the secure site.
   
   • Our communication with the candidate will request that written materials be submitted both electronically 
      through a link to our submission portal and by mail or express mail within three weeks from the date of 
      our initial email contact. Full instructions for uploading the C.V., list of publications, research proposal, 
      and three samples of work will be provided, along with a password to enter the secure site.

   • The candidate is requested to provide official transcripts of both undergraduate and graduate records. 
      (Ideally, transcripts should be forwarded directly to the Society from the universities involved; however, 
      candidates who have sealed transcripts may submit them with their mailed materials.) 
 
      On the basis of the materials submitted, the Senior Fellows select a certain number of candidates for interview. It is from this number that the final selection is made. The Society pays the traveling expenses of those candidates interviewed.

  Please note: If still pursuing the Ph.D., candidates should be at the dissertation stage of their theses and be prepared to finish their degrees within a year of becoming fellows. If already a recipient of the degree, they should not be much more than a year past the Ph.D. at the time the fellowship commences. Most Junior Fellows receive the Ph.D. just prior to the start of the fellowship.


       The deadline for receiving nominations for Junior Fellowships that begin July 1, 2018, is Friday, August 11, 2017. No nomination will be accepted with a postmark past the deadline. Nominations will not be accepted by email.
  All letters should be sent to:

  The Society of Fellows
  Harvard University
  78 Mount Auburn Street
  Cambridge, Massachusetts 02138


  Contacts  |  ©2004 President and Fellows of Harvard College
**** Harvard Academy Scholars
***** (1 Oct. 2019)
  https://academy.wcfia.harvard.edu/programs/academy_scholar
  Academy Scholars Program
  This program is open to all recent PhD recipients and doctoral candidates in the social sciences or law.

  The Academy Scholars Program identifies and supports outstanding scholars at the start of their careers whose work combines disciplinary excellence in the social sciences or law with a command of the language and history or culture of countries or regions outside of the United States or Canada. Their scholarship may elucidate domestic, comparative, or transnational issues, past or present.

  The Academy Scholars are a select community of individuals with resourcefulness, initiative, curiosity, and originality, whose work in cultures or regions outside of the US or Canada shows promise as a foundation for exceptional careers in major universities or international institutions.

  Academy Scholars are appointed for a two-year, in-residence, postdoctoral fellowship at The Harvard Academy for International and Area Studies, Harvard University, Cambridge, MA. They receive substantial financial and research assistance to undertake sustained projects of research and/or acquire accessory training in their chosen fields and areas. The Senior Scholars, a distinguished group of senior Harvard University faculty members, act as mentors to the Academy Scholars to help them achieve their intellectual potential.

  Eligibility
  The competition for these awards is open only to recent PhD (or comparable professional school degree) recipients and doctoral candidates in the social sciences or law.

  Those still pursuing a PhD should have completed their routine training and be well along in the writing of their theses before applying to become Academy Scholars. If you have completed a PhD program, the PhD completion date must be within three years of the October 1 application deadline. For applicants applying for the October 1, 2018 deadline, you must have completed your PhD or equivalent after September 30, 2015.

  The Selection Committee considers all applicants in one applicant pool.

  Terms
  Each year, four to five Academy Scholars are named for two-year appointments. Academy Scholars are expected to reside in the Cambridge/Boston area for the duration of their appointments unless traveling for pre-approved research purposes.

  Postdoctoral Academy Scholars will receive an annual stipend of $67,000. If selected before earning the PhD, the Scholars will receive an annual stipend of $31,000 until awarded the PhD. This stipend is supplemented by funding for conference and research travel, research assistants, and health insurance coverage. Some teaching is permitted but not required.

  Applications are welcome from qualified persons without regard to nationality, gender, or race

  How to Apply
  All application materials need to be submitted by the deadline of October 1. We do not accept late applications.

  The completed application will include:

  Cover letter which succinctly states the applicant's academic field, country or region of specialization, and proposed research topic
  Curriculum vitae (CV) or resumé; including list of publications
  Research proposal (2500 word maximum); including intellectual objectives and planned methodological and disciplinary work
  A copy of your PhD program transcript
  Three letters of recommendation (uploaded through the online application)
  Letters should be addressed to the "Selection Committee."
  Letters of recommendation need to be uploaded by the deadline of October 1.

  All parts of the application, including the three letters of recommendation, are submitted online as pdf documents. The online application is accessed through the homepage of The Harvard Academy’s website. To access the application, click on the APPLY ONLINE button.

  Questions should be emailed to:
  applicationinquiries@wcfia.harvard.edu.

  You may include footnotes, endnotes, and/or bibliographies in your proposed research statement, but they are not required. If you do give references, they will not count towards the 2500-word maximum for the research statement.

  We require no copies of published papers or abstracts as part of our application process. Do not include them in your application.

  Regarding transcripts from foreign universities: our reviewers read many applications from those at foreign universities and request as much transcript-like official documentation as the Registrar at your university can provide, for all graduate work—both for the Master's and PhD programs in which you have been or are currently enrolled. Your institution most likely gets these requests often and can provide the required paperwork to you upon request.
**** Environmental Fellows
**** Global American Studies Postdoctoral Fellows
     DEADLINE: <2019-11-17 Sun>
**** Inequality in America Fellows
     DEADLINE: <2019-12-01 Sun>
**** Mahindra Humanities Fellows
**** Schroeder Curatorial Fellows
**** Santo Domingo Fellows DRCLAS
     DEADLINE: <2020-01-01 Wed>
     https://drclas.harvard.edu/pages/visiting-scholarfellow-opportunities-type
*** Los Angeles
**** Faculty
***** David A. Scott (Archaeology)
      https://www.ioa.ucla.edu/people/david-scott
*** McGill
**** Mellon Postdoctoral Fellows**** Flegg Postdoctoral Fellows
*** Michigan
**** Michigan Society of Fellows
     DEADLINE: <2019-09-01 Sun>
  http://societyoffellows.umich.edu/the-fellowship/
  Each Fellow has a three-year appointment as Assistant Professor in an affiliated department of the University and a three-year appointment as a Postdoctoral Scholar in the Society of Fellows. This appointment is not tenure-track. The current annual stipend is _$60,000._ Fellows are eligible for participation in the University health, dental, and life insurance programs. Each fellow is expected to teach the equivalent of one academic year, i.e., a total of two terms during the period of the fellowship. Any subsequent appointment of a Fellow to a position at the University of Michigan would be subject to the rules governing new appointments.

  Fellows are expected to be in residence in Ann Arbor for the academic years of appointment (September to May) and to participate in the activities of the Society of Fellows. Off-campus research leave during academic terms will be permitted only in rare cases, only for brief periods of time, and only upon written application to the Chair of the Society well in advance of the proposed leave. Any leave granted will count as part of the fellowship tenure.

  Publications
  Fellows are asked to cite their affiliation with the Society of Fellows in any publications that result from work done during their tenure and to provide the Society with copies of such published work.

  Report on Scholarship
  At the end of each fellowship year, Fellows are asked to submit a written report on their activities and accomplishments during the year.

  Activities
  The Society of Fellows is an interdisciplinary intellectual community in which the postdoctoral Fellows are joined by Senior Fellows to share their work in progress. Fellows are expected to participate in monthly colloquia, attend dinners of the Society, and to engage in conversation with other members about their intellectual interests. They participate in the annual evaluation of new applicants for the Fellowship, serve as evaluators for the Distinguished Dissertations Awards sponsored by the Rackham Graduate School, and act as mentors for graduate students completing their dissertations.

  Research Assistance
  The departments of appointment have primary responsibility for providing office and laboratory or studio space for Fellows, as well as access to other research needs or equipment. The Society will help to assure the cooperation of departments in providing the requisite setting for the scholarly and creative work of each Fellow. Each Fellow may draw on the Society’s funds for research or travel on approval from the Chair and with proper receipts, up to a total of $1500 per year. Fellows are encouraged to seek support from external agencies if it appears that their scholarly and creative work will be enhanced by such grants.

  Fellowship Application
  The 2018 application will be available August 1.  Questions may be submitted to society.of.fellows@umich.edu.
**** Critical Translation Studies Fellows
*** MIT
**** SHASS Digital Humanities Fellows
https://shass.mit.edu/academics/graduate/digital-humanities-postdoc
*** New School and New York Historical Society
**** Postdoctoral Fellows
*** Oxford
**** American Institute Fellows
*** Penn
**** Mellon Postdoctoral Fellows
**** Environmental Humanities Fellows
*** Princeton
**** Princeton Society of Fellows
     DEADLINE: <2019-08-22 Thu>
  https://sf.princeton.edu/application
  The Princeton Society of Fellows in the Liberal Arts, an interdisciplinary group of scholars in the humanities, social sciences, and selected natural sciences, invites applications for the 2019-22 fellowship competition. Four fellowships will be awarded: Two Open Fellowships in any discipline represented in the Society One Fellowship in Humanistic Studies One Fellowship in LGBT Studies Applicants may apply for more than one fellowship pertinent to their research and teaching. Please see the Society’s website princeton.edu/sf/ for fellowship details, eligibility, disciplines and application. Appointed in the Humanities Council and academic departments, postdoctoral fellows pursue their research, attend weekly seminars and teach half-time as lecturers for a term of three years. In each of the first two years, fellows teach one course each semester; in their third year, only one course. The salary for 2019-2020 will be approximately _$88,800._ Fellows must reside in or near Princeton during the academic year. Applicants holding the Ph.D. at the time of application must have received the degree after January 1, 2017. Applicants not yet holding the Ph.D. must have completed a substantial portion of the dissertation - approximately half - at the time of application. Successful candidates must fulfill all requirements for the Ph.D., including filing of the dissertation, by June 15, 2019. Candidates for/recipients of doctoral degrees in Education, Jurisprudence and from Princeton University are not eligible. Applicants may apply only once to the Princeton Society of Fellows. Selection is based on exceptional scholarly achievement and evidence of unusual promise, range and quality of teaching experience, and potential contributions to an interdisciplinary community. The Society of Fellows seeks a diverse and international pool of applicants, and especially welcomes those from underrepresented backgrounds. Applicants are asked to submit an online application by August 22, 2018 (11:59 p.m. EST)
**** Judaic Studies Fellows
**** PIIRS Postdoctoral Fellows
*** San Diego State
*** Stanford
**** Mellon Fellows in the Humanities
  http://shc.stanford.edu/fellowships/mellon
  The Mellon Fellowship of Scholars in the Humanities program is a unique opportunity for the best recent PhD recipients in the humanities to develop as scholars and teachers. Up to four fellowships will be awarded for a two-year term (with the possibility of a third). Fellows teach two courses per year in one of Stanford’s fifteen humanities departments, and are expected to participate in the intellectual life of the program, which includes regular meetings with other fellows and faculty to share work in progress and to discuss topics of mutual interest. Fellows will also be affiliated with the Stanford Humanities Center and will have the opportunity to be active in its programs and workshops.

  Program admissions focus on selected fields of scholarship in each application year (on a rotating basis). We invite applicants to apply for fellowships in fields where their work has demonstrable relevance to teaching and research in the designated Stanford department. For fellowships beginning Fall 2019, applications will be accepted from the following fields of study: Classics, Feminist, Gender and Sexuality Studies, Linguistics, and Philosophy.

  The deadline to apply for fellowships beginning Fall 2019 has passed.

  Eligibility[–]
  The Mellon Fellowship provides postdoctoral fellowships in Stanford's fifteen humanities departments. Program admissions focus on selected fields of scholarship in each application year (on a rotating basis). We invite applicants to apply for fellowships in fields where their work has demonstrable relevance to teaching and research in the designated Stanford department.
  Applicants to the Mellon Fellowship cannot hold PhDs from Stanford University.
  All candidates for the Mellon Fellowship must have received a qualified PhD within a specified time frame, as follows: 2018 Competition (for fellowships beginning Autumn 2019): PhD received between January 1, 2016 and June 30, 2019. In addition to doctoral students, those currently serving as assistant professors, lecturers, or postdoctorates in other programs are welcome to apply, provided they earned their degree within the time frame specified for the year they apply. A Doctorate in Arts (DA), honorary doctorate, or any other degree equivalent is not considered a qualifed PhD for purposes of application to this program.
  Requirements[–]
  Fellows enjoy substantial time to pursue research, teach two courses per year in an affiliated Stanford Department, and participate in active program of scholarly exchanges with other Fellows, Stanford faculty, and outside visitors.
  Each Fellow is affiliated with some Stanford Humanities department, which arranges teaching and office space. This complements the Fellowship’s cross-disciplinary community by promoting Fellows’ full engagement in the activities of their home disciplines here at Stanford.  
  Fellows are expected to be in residence at Stanford for the full academic year (mid-September through mid-June), and even in quarters when they are not teaching are expected to hold regular office hours to consult with students and to participate in the academic life of the Stanford Community.
  Fellows are also expected to be active participants in the cohort of Fellows, attending regular meetings at which presentations of current work and discussions of intellectual and professional matters of interest to the group are offered.
  Application Process[–]
  Applications should be submitted via our online application system by 11:59PM PT November 1, 2018. We discourage the submission of additional materials with your application and cannot return such materials to you. Applicants will be notified when their applications have been received, and will be notified of the fellowship competition outcome in the spring. If you accept another position or postdoctoral fellowship, please withdraw your application by emailing mellonfellows@stanford.edu.
  Application Content[+]
  Stipends[–]
  The stipend for 2018-19 is $80,000. In addition to the stipend, Fellows are eligible for a full package of employee benefits and are also provided with a research account to fund research-related expenses.
**** Faculty
***** Richard White (History)
       https://history.stanford.edu/people/richard-white
***** Tanya Luhrmann (Anthropology)
**** Thinking Matters Fellows
*** Southern California
**** Middle East Postdoctoral Fellows
*** Yale
**** Cullman Postdoctoral Fellows with the NYBG
**** Humanities Fellows
**** Middle East Fellows
**** British Art Fellows
**** Faculty
***** Michael Dove
***** Paul Kockelman
*** Yale-NUS
**** Humanities Fellows 
     DEADLINE: <2019-11-30 Sat>
*** Wenner Grenn
**** Hunt Postdoctoral Fellowship
***** TODO http://www.wennergren.org/programs/hunt-postdoctoral-fellowships
*** Wesleyan
**** Mellon Humanities Fellows
**** Writing in the Social Sciences Fellows
* Term Fellowships
** [#A] Cambridge-Woolf Visiting Fellowships
*** (February 2020) Sir Mick and Lady Davis Visiting Fellowships
https://www.woolf.cam.ac.uk/about/vacancies/annual-visiting-fellowships
The Woolf Institute, which specialises in the study of relations between Jews, Christians and Muslims from a multidisciplinary perspective, invites applications for the Sir Mick and Lady Barbara Davis Visiting Fellowship.

The application deadline for 2020 has now passed.

Overview
The Fellowship is tenable for a two to three month period that overlaps one of the Cambridge terms 2020:

Lent term: 14 January–13 March 2020

Easter term: 21 April–12 June 2020

The successful candidate will be expected to be involved in a project of academic research or public education in an area relevant to the Institute's work. The Fellow will be asked to present their work at a symposium on the subject of their project proposal.

There is no stipend attached to the Fellowships, but Fellows will be entitled to free accommodation in Cambridge and one round-trip journey to Cambridge. They will also have access to the Woolf Institute and Cambridge University libraries.

The Fellowship is available for a postdoctoral scholar of any academic rank, a policymaker or analyst in a relevant area of work and will most likely be asked to participate in some of the Institute's teaching or practice-based activities. 

A letter of application, CV, the names of two referees who may be approached, a project proposal (1,500 words max.), and a sample of work should be sent to:

Electors of the Visiting Fellowship, Woolf Institute, Madingley Road, Cambridge, CB3 0UB, UK or emailed to Tina Steiner at bs411@cam.ac.uk.

Questions may be addressed informally to the Director of Research, Dr Esther-Miriam Wagner, at emw36@cam.ac.uk. 

Deadline
The application deadline has now passed. For further information, contact Dr Esther-Miriam Wagner at emw36@cam.ac.uk.
-------------------------------------------------------



