#+TITLE: Funding

* Professorships, Postdocs, & Fellowships

** American Academy of Arts and Sciences
*** Visiting Scholars Program :post:
    DEADLINE: <2019-10-01 Tue>
    https://www.amacad.org/visiting-scholars-program
** Arizona
*** Adjunct Lecturer for LATAM Drugs and Oil :job:
    DEADLINE: <2019-08-05 Mon>
https://www.timeshighereducation.com/unijobs/en-us/listing/163251/adjunct-lecturer-summer-session/
** Belfast
*** Lecturer, Education in Anthropology :prof:
    DEADLINE: <2019-08-05 Mon>
https://www.timeshighereducation.com/unijobs/en-us/listing/171265/lecturer-education-in-anthropology-/?LinkSource=PremiumListing
** Berkeley
*** President's Postdoctoral Fellows                              :post:prof:
    DEADLINE: <2019-11-11 Mon>
https://ppfp.ucop.edu/info/how-to-apply/index.html
*** Chancellor's Postdoctoral Fellows :post:prof:
    DEADLINE: <2019-11-11 Mon>

*** Ciriacy-Wantrup Postdoctoral Fellows
    DEADLINE: <2019-12-01 Sun>
https://nature.berkeley.edu/academics/ciriacy-wantrup

The S.V. Ciriacy-Wantrup Postdoctoral Fellowships in Natural Resource Economics and Political Economy will be awarded for the 2019-2020 academic year to support advanced research at the University of California, Berkeley.

For the purposes of this fellowship, natural resources are defined broadly to include environmental resources. The fellowship encourages, but is not limited to, policy-oriented research. Applications are open to scholars from any social science discipline, and related professional fields such as law and planning, who will make significant contributions to research on natural resource economics broadly defined. Preference will be given to proposals whose orientation is broadly institutional and/or historical, and which are conceptually and theoretically innovative. Proposals whose primary emphasis is on advancing statistical or econometric theory are not eligible for consideration.

The purpose of the fellowship is to develop new and innovative intellectual connections and ideas in natural resources economics and political economy at UC Berkeley. Accordingly, Applicants should provide specific information about the project proposed for the fellowship period, and explain why support from the fellowship and the opportunity to work at Berkeley are important for the success of that project. We welcome proposals from applicants who have not received their PhD at UC Berkeley. Proposals from UC Berkeley doctoral graduates that outline a significant change in research direction and that indicate engagement with different disciplines and faculty from those pursued during the doctoral program will be considered.

Two types of awards are available:

1. A one-year postdoctoral award with a salary of $58,040, renewable for a second year based on performance and funding availability. It is expected that the applicant will possess a recent doctorate or equivalent international degree by the appointment start date. Postdoctoral Fellows are appointed as UC employees and are governed by the UC Policy on Postdoctoral Scholars located here.

2. A one-year award with a salary of $58,040 to support a professional leave from an academic or professional position, without option to renew. Applicatns for visiting research fellowships must have received their doctorate or equivalent international degree within the last ten years (not including any temporary leave time due to personal or family circumstances). Applicants must provide documentation of the home institution's or agency's concurrence of their leave. Visiting Research Fellows are appointed as UC employees and are governed by the UC Policy on Visiting Appointments located here.

Both types of fellowships include $2,000 toward research-related expenses and one-way economy airfare to Berkeley for each fellow and his/her immediate family.

Application Procedure
Applications must be received by December 3, 2018.

A complete application consists of the following:

Cover Letter (Required): 1-2 page cover letter indicating your preferred Departmental affiliation and/or faculty mentor
Curriculum Vitae (Required): Your current C.V.
Abstract (Required): 1 paragraph abstract
Research proposal (Required): Not to exceed 10 pages
Publications (Required): 1 or more recent publications
Three letters of recommendation (visible to all reviewers) from faculty members familiar with the candidate's research. Applicants should ask referees to review the UC Berkeley Statement of Confidentiality
Applicants for the Visiting Research Fellowship must include a statement from their home institution concurring with the leave of absence for the duration of the fellowship term.
To Apply: 

https://aprecruit.berkeley.edu/apply/JPF01890

Questions may be directed to Ruxin Liu by e-mail at ruxinl@berkeley.eduor by phone at (510) 643-9579.

We would greatly appreciate your letting us know how you found out about this award. Send a brief note to ruxinl@berkeley.edu.

Fellowship Policies
Conditions of the Fellowship
Appointments are expected to begin one week before the academic semester begins, for one year. Adjustments for those Fellows from institutions on a different calendar will be made. The Fellow must maintain residency at the University of California, Berkeley, during the appointment period. Postdoctoral and Visiting Research Fellows are prohibited from accepting employment and augmentation of salary during this fellowship period. Violation of this condition will result in the award being revoked and reimbursement of the full award amount. However, an appointee may, without paying tuition and fees, audit classes and participate with the consent of the instructor.

Proof of Degree
Thirty days before an appointment may be confirmed, the applicant must submit a copy of an official certification showing completion of the doctoral degree or equivalent international degree, or evidence that this degree has been conferred.

Reimbursement for Travel to Berkeley
The Fellowship will pay for one-way economy airfare to Berkeley for the Fellow and his/her immediate family.

Research Allowance
The amount of $2,000 will be available to the Fellow through the host department for field research, conference travel, or related expenses such as miscellaneous office expenses, photocopying, telephone, supplies, and mailing costs. The Fellow may use the research allowance at his/her discretion within University policy.

Equipment Purchases
Fellows may choose to use their research funds to purchase equipment such as a computer and related supplies. Fellows should be aware that the University requires that all equipment purchased with University funds remain the property of the University. The Fellow may submit a request in writing to their administrating department requesting to keep the equipment.

Vacation and Academic Travel
Only one trip of more than a week’s duration may be taken during the Fall and Spring semesters for research purposes. Should a Fellow request a longer research trip that cannot be accommodated during the recess periods, a formal request should be submitted to the Chair. Subsequent travel (funds permitting) may be undertaken only if an academic paper will be delivered. The Fellow is responsible for informing their sponsoring department of their whereabouts when traveling.

Postdoctoral Research Fellows do not accrue vacation, however fellows are allowed time off each academic year in the intersession and recess periods (which constitutes about four weeks, excluding University holidays) between the beginning of Fall Term and the end of Spring Term. More information regarding leave for Potdoctoral Fellows can be located here.

Visiting Research Fellows appointed on a fiscal year basis accrue vacation at the rate of two working days per month for full-time service. Appointees at 50 percent or more time accrue vacation at a proportionate rate; appointees at less than 50 percent time do not accrue vacation. Fellows must obtain approval from their faculty mentor prior to the use of vacation leave. More information regarding vacation leave can be located here.

Health Insurance
It is expected that all fellowship recipients maintain health coverage during the entire term of the Fellowship. Eligibility for health coverage through the University is dependant on the Fellowship type.

Postdoctoral Research Fellows are covered by the UC Postdoc Scholar Benefits Plan (PSBP) and are entitled to health insurance, including dental, vision, short-term disability, life, and AD&D, through the University.

Visiting Research Fellows are covered by the UC sponsored benefits plan (Mid-level coverage) and are entitled to health insurance, including medical, life, and AD&D, through the University (AD&D plan requires an employee paid premium). Visiting Research Fellows are not entitled to dental, vision or short-term disability.

Performance Requirements
While in residence, Fellows are expected to be active participants in the academic life of their host units, through attendance at seminars relevant to their area of study and interaction with other Fellows and designated faculty mentors. Fellows are expected to give at least one seminar a year on their research in a forum to be determined in consultation with their mentor. The time and place for this seminar must be communicated to the Ciriacy-Wantrup Fellowship coordinator, Ruxin Liu, in advance with a sufficient amount of time to notify other Fellows in residence and the members of the review committee. Fellows will be expected to attend seminars given by all other Fellows. All publications written or substantially developed during the term of the fellowship must formally acknowledge the support of the Ciriacy-Wantrup Fellowship in the publication(s). A final copy of all material developed as a result of Ciriacy-Wantrup Fellowship must be submitted to the Ciriacy-Wantrup Fellowship coordinator, Ruxin Liu, for inclusion in the Ciriacy-Wantrup Fellowship library.

Renewing the Postdoctoral Wantrup Fellowship
The selection committee bases renewal decisions on evidence of progress toward the Fellow's research goals. Applications for renewal must include 1) a cover letter from the Fellow summarizing his/her progress toward the original proposal and research goals; 2) a letter of support from the Fellow's Mentor; 3) confirmation from the sponsoring Department Chair that space will continue to be available for the Fellow in the second year; and 4) copies of any papers or articles completed and/or published during the first year of the Fellowship. Supplementary items such as letters of recommendation, reports of papers delivered, or non-project-related research are all welcome if they serve to strengthen the case for renewal. Continued affiliation with the host department is at the discretion of the host department.

Administration
An additional $1,500 will be transferred to the sponsoring department to compensate their administrative efforts required for hiring, obtaining visas (when necessary), and other administrative support.

Postdoctoral appointments are governed by U.C. Policy for postdoctoral scholars (APM 390).

** Brown
*** Watson Institute Fellows
*** Presidential Diversity Fellows
*** Critical Cultural Heritage Fellows

** Cal East Bay
*** Assistant Professor of Environmental Anthropology :prof:
    DEADLINE: <2019-09-20 Fri>
http://www.csueastbay.edu/oaa/jobs/csueb.html
https://apply.interfolio.com/61640
** Cambridge
*** Davis & Woolf Visiting Fellowships
https://www.woolf.cam.ac.uk/about/vacancies/annual-visiting-fellowships
The Woolf Institute, which specialises in the study of relations between Jews, Christians and Muslims from a multidisciplinary perspective, invites applications for the Sir Mick and Lady Barbara Davis Visiting Fellowship.

The application deadline for 2020 has now passed.

Overview
The Fellowship is tenable for a two to three month period that overlaps one of the Cambridge terms 2020:

Lent term: 14 January–13 March 2020

Easter term: 21 April–12 June 2020

The successful candidate will be expected to be involved in a project of academic research or public education in an area relevant to the Institute's work. The Fellow will be asked to present their work at a symposium on the subject of their project proposal.

There is no stipend attached to the Fellowships, but Fellows will be entitled to free accommodation in Cambridge and one round-trip journey to Cambridge. They will also have access to the Woolf Institute and Cambridge University libraries.

The Fellowship is available for a postdoctoral scholar of any academic rank, a policymaker or analyst in a relevant area of work and will most likely be asked to participate in some of the Institute's teaching or practice-based activities. 

A letter of application, CV, the names of two referees who may be approached, a project proposal (1,500 words max.), and a sample of work should be sent to:

Electors of the Visiting Fellowship, Woolf Institute, Madingley Road, Cambridge, CB3 0UB, UK or emailed to Tina Steiner at bs411@cam.ac.uk.

Questions may be addressed informally to the Director of Research, Dr Esther-Miriam Wagner, at emw36@cam.ac.uk. 

Deadline
The application deadline has now passed. For further information, contact Dr Esther-Miriam Wagner at emw36@cam.ac.uk.
-------------------------------------------------------

*** Career Development Fellows
*** Post-doctoral fellowships
    https://www.socanth.cam.ac.uk/socanth-research/post-doc-funding
** Chicago
*** Chicago Society of Fellows
**** (x Sept. 2019)
 https://societyoffellows.uchicago.edu/https%3A//fellows.uchicago.edu

*** Chicago Provost's Fellows
https://provostpostdoc.uchicago.edu/
** Columbia
*** Earth Institute Fellows :post:
    DEADLINE: <2019-10-30 Wed>    https://applyeiprograms.smapply.io/prog/ei_postdoctoral_research_program/
*** Faculty
**** Ben Orlove
**** Paige West
**** Rashid Khalidi
**** Bryan Boyd
** Cornell
*** Cornell Mellon Fellows :post:
    DEADLINE: <2019-10-01 Tue> https://societyhumanities.as.cornell.edu/mellon-postdoctoral-fellowships
** Dartmouth
*** Dartmouth Humanities Fellows :post:
    DEADLINE: <2019-09-16 Mon>
    https://www.dartmouth.edu/sof/fellowships/postdoc.html
*** McKennen Anthropology Fellows :post:
    DEADLINE: <2019-08-31 Sat>
    Deadline unknown needs re-checking. 
https://anthropology.dartmouth.edu/research/mckennan-postdoc-fellowship
** Harvard
*** Academic Positions Database
https://academicpositions.harvard.edu/
*** Bullard Fellowship in Forest Research :post:
    DEADLINE: <2020-01-15 Wed>
https://harvardforest.fas.harvard.edu/mid-career-fellowships#apply ; 
https://www.grantforward.com/grant/sample_grant?grant_id=340256

*** Harvard Society of Fellows :post:
     Nominations DEADLINE: <2019-08-09 Fri>
https://socfell.fas.harvard.edu/nomination-procedure
*** Harvard Academy Scholars :post:
    DEADLINE: <2019-10-01 Tue>
 https://academy.wcfia.harvard.edu/programs/academy_scholar
 Academy Scholars Program
*** Center for Environment Fellows :post:
    DEADLINE: <2020-01-16 Thu> http://environment.harvard.edu/environmental-fellows-program
*** Global American Studies Fellows :post:
    DEADLINE: <2019-11-17 Sun>
*** Inequality in America Fellows :post:
    DEADLINE: <2019-12-01 Sun> 
2019 Deadline will be announced in September;    https://inequalityinamerica.fas.harvard.edu/postdoctoral-program
*** Mahindra Humanities Fellows :post:
    DEADLINE: <2019-11-05 Tue>
http://mahindrahumanities.fas.harvard.edu/content/postdoctoral-fellowships
*** Schroeder Curatorial Fellows :post:
Search web for current advertisement
*** Santo Domingo Fellows DRCLAS :post:
    DEADLINE: <2020-01-01 Wed> https://drclas.harvard.edu/pages/visiting-scholarfellow-opportunities-type
*** Professor in Islamic Studies :prof:
    DEADLINE: <2019-08-10 Sat>
https://www.timeshighereducation.com/unijobs/en-us/listing/171755/professor-assistant-associate-in-islamic-studies-/?LinkSource=TopJob
** Los Angeles
*** Faculty
**** David A. Scott (Archaeology)
     https://www.ioa.ucla.edu/people/david-scott
** McGill
*** Mellon Postdoctoral Fellows
*** Flegg Postdoctoral Fellows
** Michigan
*** Michigan Society of Fellows :post:
    DEADLINE: <2019-09-01 Sun>
 http://societyoffellows.umich.edu/the-fellowship/
*** President's Postdoctoral Fellows :post:
    DEADLINE: <2019-11-01 Fri>
http://presidentspostdoc.umich.edu/
*** LSA Collegiate Fellows :post:prof:
    DEADLINE: <2019-10-01 Tue>
https://lsa.umich.edu/ncid/fellowships-awards/lsa-collegiate-postdoctoral-fellowship.html
*** Critical Translation Studies Fellows
** MIT
*** SHASS Digital Humanities Fellows
https://shass.mit.edu/academics/graduate/digital-humanities-postdoc
** New School and New York Historical Society
*** Postdoctoral Fellows
** Oxford
*** American Institute Fellows
** Penn
*** Mellon Postdoctoral Fellows
*** Environmental Humanities Fellows
** Princeton
*** Princeton Society of Fellows
    DEADLINE: <2019-08-22 Thu>
 https://sf.princeton.edu/application
 The Princeton Society of Fellows in the Liberal Arts, an interdisciplinary group of scholars in the humanities, social sciences, and selected natural sciences, invites applications for the 2019-22 fellowship competition. Four fellowships will be awarded: Two Open Fellowships in any discipline represented in the Society One Fellowship in Humanistic Studies One Fellowship in LGBT Studies Applicants may apply for more than one fellowship pertinent to their research and teaching. Please see the Society’s website princeton.edu/sf/ for fellowship details, eligibility, disciplines and application. Appointed in the Humanities Council and academic departments, postdoctoral fellows pursue their research, attend weekly seminars and teach half-time as lecturers for a term of three years. In each of the first two years, fellows teach one course each semester; in their third year, only one course. The salary for 2019-2020 will be approximately _$88,800._ Fellows must reside in or near Princeton during the academic year. Applicants holding the Ph.D. at the time of application must have received the degree after January 1, 2017. Applicants not yet holding the Ph.D. must have completed a substantial portion of the dissertation - approximately half - at the time of application. Successful candidates must fulfill all requirements for the Ph.D., including filing of the dissertation, by June 15, 2019. Candidates for/recipients of doctoral degrees in Education, Jurisprudence and from Princeton University are not eligible. Applicants may apply only once to the Princeton Society of Fellows. Selection is based on exceptional scholarly achievement and evidence of unusual promise, range and quality of teaching experience, and potential contributions to an interdisciplinary community. The Society of Fellows seeks a diverse and international pool of applicants, and especially welcomes those from underrepresented backgrounds. Applicants are asked to submit an online application by August 22, 2018 (11:59 p.m. EST)
*** Judaic Studies Fellows
*** PIIRS Postdoctoral Fellows
** San Diego State
*** Anthropologist in Science and Technology Studies :prof:
    DEADLINE: <2019-09-15 Sun>
https://apply.interfolio.com/64831

** Stanford
*** Mellon Fellows in the Humanities
 http://shc.stanford.edu/fellowships/mellon
 The Mellon Fellowship of Scholars in the Humanities program is a unique opportunity for the best recent PhD recipients in the humanities to develop as scholars and teachers. Up to four fellowships will be awarded for a two-year term (with the possibility of a third). Fellows teach two courses per year in one of Stanford’s fifteen humanities departments, and are expected to participate in the intellectual life of the program, which includes regular meetings with other fellows and faculty to share work in progress and to discuss topics of mutual interest. Fellows will also be affiliated with the Stanford Humanities Center and will have the opportunity to be active in its programs and workshops.

 Program admissions focus on selected fields of scholarship in each application year (on a rotating basis). We invite applicants to apply for fellowships in fields where their work has demonstrable relevance to teaching and research in the designated Stanford department. For fellowships beginning Fall 2019, applications will be accepted from the following fields of study: Classics, Feminist, Gender and Sexuality Studies, Linguistics, and Philosophy.

 The deadline to apply for fellowships beginning Fall 2019 has passed.

 Eligibility[–]
 The Mellon Fellowship provides postdoctoral fellowships in Stanford's fifteen humanities departments. Program admissions focus on selected fields of scholarship in each application year (on a rotating basis). We invite applicants to apply for fellowships in fields where their work has demonstrable relevance to teaching and research in the designated Stanford department.
 Applicants to the Mellon Fellowship cannot hold PhDs from Stanford University.
 All candidates for the Mellon Fellowship must have received a qualified PhD within a specified time frame, as follows: 2018 Competition (for fellowships beginning Autumn 2019): PhD received between January 1, 2016 and June 30, 2019. In addition to doctoral students, those currently serving as assistant professors, lecturers, or postdoctorates in other programs are welcome to apply, provided they earned their degree within the time frame specified for the year they apply. A Doctorate in Arts (DA), honorary doctorate, or any other degree equivalent is not considered a qualifed PhD for purposes of application to this program.
 Requirements[–]
 Fellows enjoy substantial time to pursue research, teach two courses per year in an affiliated Stanford Department, and participate in active program of scholarly exchanges with other Fellows, Stanford faculty, and outside visitors.
 Each Fellow is affiliated with some Stanford Humanities department, which arranges teaching and office space. This complements the Fellowship’s cross-disciplinary community by promoting Fellows’ full engagement in the activities of their home disciplines here at Stanford.  
 Fellows are expected to be in residence at Stanford for the full academic year (mid-September through mid-June), and even in quarters when they are not teaching are expected to hold regular office hours to consult with students and to participate in the academic life of the Stanford Community.
 Fellows are also expected to be active participants in the cohort of Fellows, attending regular meetings at which presentations of current work and discussions of intellectual and professional matters of interest to the group are offered.
 Application Process[–]
 Applications should be submitted via our online application system by 11:59PM PT November 1, 2018. We discourage the submission of additional materials with your application and cannot return such materials to you. Applicants will be notified when their applications have been received, and will be notified of the fellowship competition outcome in the spring. If you accept another position or postdoctoral fellowship, please withdraw your application by emailing mellonfellows@stanford.edu.
 Application Content[+]
 Stipends[–]
 The stipend for 2018-19 is $80,000. In addition to the stipend, Fellows are eligible for a full package of employee benefits and are also provided with a research account to fund research-related expenses.
*** Faculty
**** Richard White (History)
      https://history.stanford.edu/people/richard-white
**** Tanya Luhrmann (Anthropology)
*** Thinking Matters Fellows
*** Editorial Assistant Stanford Univ Press :job:
    DEADLINE: <2019-07-21 Sun>
https://www.timeshighereducation.com/unijobs/en-us/listing/169473/editorial-assistant/
** Smithsonian Tropical Research Institute
*** E.S. Tupper Three-year Postdoc
    DEADLINE: <2019-08-15 Thu>
    https://www.grantforward.com/grant?grant_id=339623&offset=2
    https://stri.si.edu/sites/default/files/3year_tupper_postdocad.pdf
    https://solaa.si.edu/
** Southern California
*** Middle East Postdoctoral Fellows
** Yale
*** Postdocs List:
https://postdocs.yale.edu/yale-postdoctoral-positions
*** Cullman-NYBG Postdoc :post:
    DEADLINE: <2020-12-20 Sun>
*** Humanities Fellows
*** Middle East Fellows
*** [#C] Study of Slavery, Resistance, and Abolition 
*** Faculty
**** Michael Dove
**** Paul Kockelman
** Yale-NUS
*** Humanities Fellows 
    DEADLINE: <2019-11-30 Sat>
** Wenner Grenn
*** Hunt Postdoctoral Fellowship :post:
http://www.wennergren.org/programs/hunt-postdoctoral-fellowships
     DEADLINE: <2020-05-01 Fri>
** Wesleyan
*** Mellon Humanities Fellows
*** Writing in the Social Sciences Fellows

* Finding Aids
American Anthropological Association: http://careercenter.aaanet.org/jobs ; GrantFoward: https://www.grantforward.com ; Jobs UK: https://jobs.ac.uk ; Academic Positions EU: https://academicpositions.com ; Times Higher Education Job Postings https://www.timeshighereducation.com/unijobs/en-us/listings/academic-posts/?Keywords=anthropology#browsing
