#+TITLE: Funding
#+DATE: 

* Professorships, Postdocs, & Fellowships
KEY:
a "job" is a non-tenure track, limited time position;
a "post" is a post-doc of any kind
a "prof" is a professorship with tenure-track
a "post:prof" is a post-doc with a road to tenure track
** American Academy of Arts and Sciences :post:
*** Visiting Scholars Program :post:
    DEADLINE: <2019-10-01 Tue>
    https://www.amacad.org/visiting-scholars-program
*** Science and Technology Policy Fellows
    DEADLINE: <2019-11-01 Fri>
    http://go.stpf-aaas.org/socialscience.html
** Bergen :prof:
*** Associate Professor of Anthropology :prof:
    DEADLINE: <2019-09-15 Wed>    https://www.jobbnorge.no/en/available-jobs/job/172971/associate-professor-in-social-anthropology
** Berkeley :post:prof:
*** President's Postdoctoral Fellows :post:prof:
    DEADLINE: <2019-11-11 Mon>
    https://ppfp.ucop.edu/info/how-to-apply/index.html
*** Chancellor's Postdoctoral Fellows :post:prof:
    DEADLINE: <2019-11-11 Mon>
*** Ciriacy-Wantrup Postdoctoral Fellows :post:
    DEADLINE: <2019-12-01 Sun>
    https://nature.berkeley.edu/academics/ciriacy-wantrup
    https://aprecruit.berkeley.edu/apply/JPF01890
** Bowdoin :prof:
*** Two Tenure-Track Sociocultural Anthropology                        :prof:
    DEADLINE: <2019-09-15 Sun>
    https://careers.bowdoin.edu/postings/6278
    to Dove: mailspring://thread?subject=%5BDove-docs%5D%20Fwd%3A%20two%20positions%20of%20interest&date=1566396338
** Brown :prof:
*** Professor of Anthropology and International and Public Affairs :prof:
    DEADLINE: <2019-10-15 Tue>
    http://apply.interfolio.com/65294
    http://careercenter.americananthro.org/jobs/12579316/professor-of-anthropology-and-international-and-public-affairs?utm_source=BTITwitter&utm_medium=Twitter&utm_campaign=BTI%2BTwitter%2BFeed
*** Watson Institute Fellows
*** Presidential Diversity Fellows
*** Critical Cultural Heritage Fellows
** Cal East Bay :prof:
*** Assistant Professor of Environmental Anthropology :prof:
    DEADLINE: <2019-09-20 Fri>
    http://www.csueastbay.edu/oaa/jobs/csueb.html
    https://apply.interfolio.com/61640
** Cambridge
*** Davis & Woolf Visiting Fellowships
    https://www.woolf.cam.ac.uk/about/vacancies/annual-visiting-fellowships
*** Career Development Fellows
*** St John's College Research Fellowships :post:
    DEADLINE: <2019-10-01 Tue>
    https://sjcamrf.flexigrant.com/
*** Post-doctoral fellowships
    https://www.socanth.cam.ac.uk/socanth-research/post-doc-funding
** Chicago
*** Collegiate Professors
    DEADLINE: <2019-10-11 Fri>
    http://careercenter.aaanet.org/jobs/12659220/collegiate-assistant-professor
*** Chicago Society of Fellows
**** (x Sept. 2019)
     https://societyoffellows.uchicago.edu/https%3A//fellows.uchicago.edu
*** Chicago Provost's Fellows
    https://provostpostdoc.uchicago.edu/
** Columbia
*** Earth Institute Fellows :post:
    DEADLINE: <2019-10-30 Wed>    https://applyeiprograms.smapply.io/prog/ei_postdoctoral_research_program/
*** Faculty
**** Ben Orlove
**** Paige West
**** Rashid Khalidi
**** Bryan Boyd
** Cornell :post:prof:
*** Assistant Prof of Science and Technology :prof:
    DEADLINE: <2019-11-01 Fri>
    https://academicjobsonline.org/ajo/jobs/14248
*** Cornell Mellon Fellows :post:
    DEADLINE: <2019-10-01 Tue> https://societyhumanities.as.cornell.edu/mellon-postdoctoral-fellowships
** Dartmouth :post:
*** Dartmouth Society of Fellows                                       :post:
    DEADLINE: <2019-09-16 Mon>
    https://www.dartmouth.edu/sof/fellowships/postdoc.html
*** McKennen Anthropology Fellows :post:
    DEADLINE: <2019-08-31 Sat>
    Deadline unknown needs re-checking. 
https://anthropology.dartmouth.edu/research/mckennan-postdoc-fellowship
** Davidson :prof:
*** Tenure Track Assistant Prof in Environmental Change and Society :prof:
    DEADLINE: <2019-10-01 Tue>
    https://www.davidson.edu/news/2019/07/30/tenure-track-position-environmental-studies
** El Paso :prof:
*** Assistant Professor of Anthropology :prof:
    mailspring://thread?subject=Tenure-track%20job%20at%20UTEP&date=1566418960
** Ford Foundation :post:
*** Postdoctoral Fellowships :post:
    SCHEDULED: <2019-11-20 Wed> DEADLINE: <2019-12-10 Tue>
    https://www.grantforward.com/grant?grant_id=337866
** Geneva :prof:
*** Assistant Professor of Gender and Development :prof:
   DEADLINE: <2019-08-31 Sat>
   https://www.jobs.ac.uk/job/BTW834/assistant-professor-of-anthropology-sociology-of-gender-and-development
** Goldsmiths :prof:
*** Lecturer in Anthropology :prof:
    https://www.jobs.ac.uk/job/BUG947/lecturer-in-anthropology
** Harvard
*** Academic Positions Database :post:prof:
    https://academicpositions.harvard.edu/
*** Bullard Fellowship in Forest Research :post:
    DEADLINE: <2020-01-15 Wed>
    https://harvardforest.fas.harvard.edu/mid-career-fellowships#apply ; 
    https://www.grantforward.com/grant/sample_grant?grant_id=340256
*** Harvard Society of Fellows :post:
     Nominations DEADLINE: <2019-08-09 Fri>
     https://socfell.fas.harvard.edu/nomination-procedure
*** Harvard Academy Scholars :post:
    DEADLINE: <2019-10-01 Tue>
    https://academy.wcfia.harvard.edu/programs/academy_scholar
    Academy Scholars Program
*** Academy for International and Area Studies Postdoc :post:
    DEADLINE: <2019-10-01 Tue>
    http://careercenter.aaanet.org/jobs/12691007/harvard-academy-for-international-and-area-studies-postdoc
*** Center for Environment Fellows :post:
    DEADLINE: <2020-01-16 Thu> http://environment.harvard.edu/environmental-fellows-program
*** Global American Studies Fellows :post:
    DEADLINE: <2019-11-17 Sun>
*** Inequality in America Fellows :post:
    DEADLINE: <2019-12-01 Sun> 
    2019 Deadline will be announced in September;    https://inequalityinamerica.fas.harvard.edu/postdoctoral-program
*** Mahindra Humanities Fellows :post:
    DEADLINE: <2019-11-05 Tue>
    http://mahindrahumanities.fas.harvard.edu/content/postdoctoral-fellowships
*** Schroeder Curatorial Fellows :post:
    Search web for current advertisement
*** Santo Domingo Fellows DRCLAS :post:
    DEADLINE: <2020-01-01 Wed> https://drclas.harvard.edu/pages/visiting-scholarfellow-opportunities-type
** Laussanne
*** TODO [#A] Assistant Professor in Societal Challenges of Climate Change Impacts :prof:
    SCHEDULED: <2019-07-29 Mon> DEADLINE: <2019-09-25 Wed>
    https://academicpositions.com/ad/university-of-lausanne/2019/assistant-professor-tenure-track-in-societal-challenges-of-climate-change-impacts/131626
** Indiana
*** Assistant or Associate Professor, Sustainable Food Systems
    SCHEDULED: <2019-08-24 Sat> DEADLINE: <2019-09-01 Sun>
    http://indiana.peopleadmin.com/postings/7876
** Los Angeles
*** Faculty
**** David A. Scott (Archaeology)
     https://www.ioa.ucla.edu/people/david-scott
** Manchester :post:
*** Research Fellowship in Socio-Environmental Systems :post:
    DEADLINE: <2019-10-06 Sun>
    https://www.jobs.ac.uk/job/BUR976/research-fellowship-in-socio-environmental-systems
** Maryland :prof:
   DEADLINE: <2019-10-27 Sun>
   http://careercenter.aaanet.org/jobs/12724910/assistant-professor
** McGill
*** Mellon Postdoctoral Fellows :post:
    DEADLINE: <2019-11-26 Tue>
    https://www.mcgill.ca/arts/research/fellowships/mellon
*** Flegg Postdoctoral Fellows :post:
** McMaster
*** Assistant Prof. Sociocultural :prof:
    DEADLINE: <2019-11-01 Fri>
    http://careercenter.aaanet.org/jobs/12698385/assistant-professor-social-cultural-anthropology
** Michigan
*** Michigan Society of Fellows :post:
    DEADLINE: <2019-09-01 Sun>
    http://societyoffellows.umich.edu/the-fellowship/
*** President's Postdoctoral Fellows :post:
    DEADLINE: <2019-11-01 Fri>
    http://presidentspostdoc.umich.edu/
*** LSA Collegiate Fellows :post:prof:
    DEADLINE: <2019-10-01 Tue>
    https://lsa.umich.edu/ncid/fellowships-awards/lsa-collegiate-postdoctoral-fellowship.html
*** Critical Translation Studies Fellows
** Michigan State
*** TODO Research Associate with Tenure Track                     :post:prof:
    DEADLINE: <2019-08-28 Wed>
    http://careercenter.aaanet.org/jobs/12526529/research-associate
** MIT
*** SHASS Digital Humanities Fellows
    https://shass.mit.edu/academics/graduate/digital-humanities-postdoc
** New School and New York Historical Society
*** Postdoctoral Fellows
** Notre Dame
*** Assist. Prof in Environmental Policy
    DEADLINE: <2019-11-01 Fri>
    https://apply.interfolio.com/66421
** Oxford :post:job:
*** Stipendiary Lectureship in Anthropology :job:
    DEADLINE: <2019-09-06 Fri>
    https://www.jobs.ac.uk/job/BUD663/stipendiary-lecturership-in-social-and-cultural-anthropology
*** American Institute Fellows
*** Oxford Centre for Islamic Studies :post:
    DEADLINE: <2019-08-29 Thu>
    https://www.jobs.ac.uk/job/BTX710/research-fellowships
** Penn
*** Mellon Postdoctoral Fellows
*** Environmental Humanities Fellows
** Princeton :prof:post:
*** Tenure-Track Assistant Professor                                   :prof:
    DEADLINE: <2019-10-04 Fri>
    https://puwebp.princeton.edu/AcadHire/apply/application.xhtml?listingId=12581
*** Tenure-Track Assist. Prof. Environmental Humanities :prof:
    DEADLINE: <2019-10-05 Sat>
    https://www.princeton.edu/acad-positions/position/13221
*** Princeton Society of Fellows                                       :post:
    DEADLINE: <2019-08-22 Thu>
    https://sf.princeton.edu/application
*** Woodrow Wilson Values and Public Policy Fellows                    :post:
    DEADLINE: <2019-11-11 Mon>
    Two year position. Should associate with a center or program, see: http://wws.princeton.edu/centers-programs.
    Application info: https://uchv.princeton.edu/academic-programs/postdoctoral-research-associate-values-and-public-policy
*** PIIRS Postdoctoral Fellows
** Puget Sound
*** Assistant Professor of Anthropology
    DEADLINE: <2019-09-30 Mon>
    https://www2.pugetsound.jobs/psc/HRPRD/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_APP_SCHJOB.GBL?FOCUS=Applicant&siteid=3&
** San Diego State :prof:
*** Anthropologist in Science and Technology Studies                   :prof:
    DEADLINE: <2019-09-15 Sun>
    https://apply.interfolio.com/64831
** Stanford :post:prof:
*** Assistant Professor in Social Science of Muslim Societies :prof:
*** Mellon Fellows in the Humanities
    http://shc.stanford.edu/fellowships/mellon
**** Faculty
**** Richard White (History)
     https://history.stanford.edu/people/richard-white
**** Tanya Luhrmann (Anthropology)
*** King Center in Global Development :post:
    DEADLINE: <2019-12-01 Sun>
    https://chroniclevitae.com/jobs/0000501196-01?cid=VTEVPMSJOB1
*** Thinking Matters Fellows

** Smithsonian Tropical Research Institute
*** DONE E.S. Tupper Three-year Postdoc
    DEADLINE: <2019-08-15 Thu>
    https://www.grantforward.com/grant?grant_id=339623&offset=2
    https://stri.si.edu/sites/default/files/3year_tupper_postdocad.pdf
    https://solaa.si.edu/
** Southern California
*** Middle East Postdoctoral Fellows
** Temple
*** TT Assis. Prof. in Energy Geography
    DEADLINE: <2019-10-01 Tue>
    https://apply.interfolio.com/67134
    mailspring://thread?subject=%5BPesoemails%5D%20Assistant%20Professor%20in%20Energy%20Geography%20at%20Temple%20University&date=1566420324
** Victoria :prof:
*** Assistant Prof. Anthropology Indigenous Scholarship :prof:
    DEADLINE: <2019-10-18 Fri>
    http://careercenter.aaanet.org/jobs/12667660/assistant-or-associate-professor-in-anthropology-indigenous-scholar
** Yale
*** Academic Positions Database
    https://postdocs.yale.edu/yale-postdoctoral-positions
*** Cullman-NYBG Postdoc :post:
    DEADLINE: <2020-12-20 Sun>
*** Humanities Fellows
*** Middle East Fellows
*** [#C] Study of Slavery, Resistance, and Abolition 
*** Faculty
**** Michael Dove
**** Paul Kockelman
** Yale-NUS
*** Tenure-Track Assistant Professor in Anthropology :prof:
    DEADLINE: <2019-10-31 Thu>
    mailspring://thread?subject=FW%3A%20Tenure-Track%20Assistant%20Professor%20Position%20in%20Anthropology%20at%20Yale-NUS%20College%20Posted&date=1564073938
*** Humanities Fellows :post:
    DEADLINE: <2019-11-30 Sat>
** York
*** Anthropology of Race, Racisms, and Racialization :prof:
    DEADLINE: <2019-10-15 Tue>
    http://careercenter.aaanet.org/jobs/12703129/anthropology-of-race-racisms-and-racialization
** Waikato
*** DONE Lecturer in Anthropology
    DEADLINE: <2019-07-31 Wed>
    https://www.waikato.ac.nz/vacancies/current-vacancies
** Wenner Grenn
*** Hunt Postdoctoral Fellowship :post:
    http://www.wennergren.org/programs/hunt-postdoctoral-fellowships
     DEADLINE: <2020-05-01 Fri>
** Wesleyan
*** Mellon Humanities Fellows
*** Writing in the Social Sciences Fellows

** Western Colorado
*** TT Assist. Prof. Env. and Sust.                                    :prof:
    DEADLINE: <2019-09-01 Sun>
    https://www.western.edu/human-resources/faculty-and-exempt-job-announcements
** Wooster College :prof:
*** TT A. Prof. Sociology and Anthropology :prof:
    DEADLINE: <2019-11-10 Sun>
    http://apply.interfolio.com/65967
* Finding Aids
  American Anthropological Association: http://careercenter.aaanet.org/jobs ;
  GrantFoward: https://www.grantforward.com ;
  Jobs UK: https://jobs.ac.uk ;
  Academic Positions EU: https://academicpositions.com ;
  Times Higher Education Job Postings https://www.timeshighereducation.com/unijobs/en-us/listings/academic-posts/?Keywords=anthropology#browsing
  Academic Wiki of Soc. Sci. Humanities Post-Docs: https://academicjobs.wikia.org/wiki/Humanities_and_Social_Sciences_Postdocs_2019-2020 ; 


